### ISSUE TITLE
Exception on execution

### ISSUE THREAD

**Issue by TahaR9** [Saket-Upadhyay/Android-Permission-Extraction-and-Dataset-Creation-with-Python#4]
![image](https://user-images.githubusercontent.com/26572894/98511128-1b111b00-2286-11eb-8998-4fec07daede0.png)

It is going in exception for some reason, what is the reason?

**Comment by Saket-Upadhyay** [comment]
It seems like it is running on windows enviornment but the scripts and supporting binaries are set up for Linux enviornment, that's why I think it's throwing errors. That's that most common cause. 

Please try once in any 64bit Linux enviornment like Ubuntu, Kali,  Fedora, etc.

**Comment by TahaR9** [comment]
Ahh, thought it was for windows.

**Comment by sunnie39** [comment]
I had the same error as that.
please Let me know what the problem is.
It would be nice if you could tell me specifically about the operating system and the environment version (ex. java, python, JNI, etc..)
