### ISSUE TITLE
where is updatePermList.txt?

### ISSUE THREAD

**Issue by xeon-a** [Saket-Upadhyay/Android-Permission-Extraction-and-Dataset-Creation-with-Python#5]
i tried this project. but apkError and EERRRROORR appear.

-

**Comment by Saket-Upadhyay** [comment]
It is a feature, if you want to add more permissions/custom permission in the DefaultPerm list then you can create updatePermList.txt and it will append that into the default list. It is not critical to base operation though.

**Comment by xeon-a** [comment]
ok. i see. but base operation doesn't work. what is the problem? i do this project in ubuntu 20.04, python3. i tried to download all project zip file. and i do the code 'python3 ExtractorAIO.py'. but apkError and EERRROORR appear. i don't know why.

**Comment by Saket-Upadhyay** [comment]
Please check you have some APK files in respective folders, also check your JAVA and JADX path. 

There are some issues with new android packages though, but packages packed before Nov,2020 should work fine.

**Comment by Saket-Upadhyay** [comment]
I am closing this issue as it is about updatePermList.txt, but feel free to create another for different issue, this will help others to solve the problems you are facing. ^\_^
