### ISSUE TITLE
can u please Provide me The code for windows environment

### ISSUE THREAD

**Issue by sudharsan-16** [Saket-Upadhyay/Android-Permission-Extraction-and-Dataset-Creation-with-Python#7]
can u please Provide me The code for windows environment

**Comment by Saket-Upadhyay** [comment]
Hello, 

I am currently overwhelmed by academic and other stuff, that's why not able to give much time to this project.

I will try to port this to **docker** as soon as I get some time, but there is no Windows Specific code so far.

**Comment by sudharsan-16** [comment]
there are some errors when i run this code on Windows and couldn't solve that as im using this for my fyp couldnt find another better feature extraction code for android

**Comment by Saket-Upadhyay** [comment]
The errors are there because some 3rd party modules used (JADX) are for Linux (ELF format) hence they can't run in windows.
